name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: huuhka.azurecr.io
          username: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
          password: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: huuhka.azurecr.io/t-painbot:${{ steps.date.outputs.date }}